<?php
$fetchdesc = array (
  'params' => 
  array (
    'object_attribute_id' => 
    array (
      'type' => 'integer',
      'required' => false,
      'desc' => 'The ID number of the target object attribute.',
    ),
    'object_id' => 
    array (
      'type' => 'integer',
      'required' => false,
      'desc' => 'The ID number of the target content object.',
    ),
    'value' => 
    array (
      'type' => 'integer',
      'required' => false,
      'desc' => 'Value filtering on the attribute level.',
    ),
    'creator_id' => 
    array (
      'type' => 'integer',
      'required' => false,
      'desc' => 'The creator of the information. Only used when object_id is used',
    ),
    'user_identifier' => 
    array (
      'type' => 'string',
      'required' => false,
      'desc' => 'The user identification string generated by eZ Publish when the information was collected. Only used when object_id is used',
    ),
  ),
  'return' => 'The number of collections (as an integer).',
  'desc' => 'Fetches the number of collections that match a certain criteria.',
);
?>